[tool.poetry]
name = "aoc"
version = "0.1.0"
description = "minimum packages required"
authors = ["Hinny Tsang"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.8"
pylint = "^2.15.8"

[tool.poetry.dev-dependencies]
pylint = "^2.4.4"

[build-system]
requires = ["poetry>=0.12"]
